### ISSUE TITLE
how to set only one species as foreground

### ISSUE THREAD

**Issue by zsdxgl** [lauguma/GWideCodeML#1]
Dear lauguma,

WGideCodeML is a great work. However, when I set only one species as foreground, error appears as below:

Traceback (most recent call last):
  File "/DATA5/software/miniconda/envs/gwcodeml/bin/gwidecodeml", line 33, in <module>
    sys.exit(load_entry_point('gwidecodeml==1.1', 'console_scripts', 'gwidecodeml')())
  File "/DATA5/software/miniconda/envs/gwcodeml/lib/python3.6/site-packages/gwidecodeml-1.1-py3.6.egg/gwidecodeml/__main__.py", line 134, in main
  File "/DATA5/software/miniconda/envs/gwcodeml/lib/python3.6/site-packages/gwidecodeml-1.1-py3.6.egg/gwidecodeml/pkg_utils/utils.py", line 141, in prepare_codeml
  File "/DATA5/software/miniconda/envs/gwcodeml/lib/python3.6/site-packages/gwidecodeml-1.1-py3.6.egg/gwidecodeml/pkg_utils/utils.py", line 517, in mark_branches
AttributeError: 'str' object has no attribute 'node_id'

This error alos happens in the example, when only one species selected as foreground. How to set only one species as foreground ?

Best,
Leon
zsdxgl@163.com

**Comment by lauguma** [comment]
Dear Leon,

Thank you for using GWideCodeML and for reporting the issue.
Your problem was due to a bug in the code that has been fixed. You can now use the package for testing hypothesis in a single species. To do it, please, download and install GWideCodeML again as specified in the instructions. 
Please feel free to contact me if you need any further information.

Laura
laugmacias@gmail.com

**Comment by zsdxgl** [comment]
Thanks very much.

Another question: Can the species name cantain "_"  ？

**Comment by lauguma** [comment]
Hi Leon,
The species name should not contain a "_". Otherwise, the package will take the name before the underscore as a species name, and if it does not match the name in the species tree, it will give rise an error.
