### ISSUE TITLE
there is an error when i try to run GWideCodeML

### ISSUE THREAD

**Issue by yananzh** [lauguma/GWideCodeML#3]
Traceback (most recent call last):
  File "/home/zhangyanan/miniconda3/envs/gwcodeml/bin/gwidecodeml", line 33, in <module>
    sys.exit(load_entry_point('gwidecodeml==1.1', 'console_scripts', 'gwidecodeml')())
  File "/home/zhangyanan/miniconda3/envs/gwcodeml/lib/python3.6/site-packages/gwidecodeml-1.1-py3.6.egg/gwidecodeml/__main__.py", line 82, in main
  File "/home/zhangyanan/miniconda3/envs/gwcodeml/lib/python3.6/site-packages/gwidecodeml-1.1-py3.6.egg/gwidecodeml/pkg_utils/utils.py", line 55, in dup_tags
  File "/home/zhangyanan/miniconda3/envs/gwcodeml/lib/python3.6/site-packages/biopython-1.78-py3.6-linux-x86_64.egg/Bio/SeqIO/__init__.py", line 607, in parse
    return iterator_generator(handle)
  File "/home/zhangyanan/miniconda3/envs/gwcodeml/lib/python3.6/site-packages/biopython-1.78-py3.6-linux-x86_64.egg/Bio/SeqIO/FastaIO.py", line 183, in __init__
    super().__init__(source, mode="t", fmt="Fasta")
  File "/home/zhangyanan/miniconda3/envs/gwcodeml/lib/python3.6/site-packages/biopython-1.78-py3.6-linux-x86_64.egg/Bio/SeqIO/Interfaces.py", line 47, in __init__
    self.stream = open(source, "r" + mode)

**Comment by Sher-Ojala** [comment]
I am getting that same error.  Any ideas?
Thanks!

**Comment by lijunyuan** [comment]
Also confronting the same error while testing the example data, please help!

**Comment by Sher-Ojala** [comment]
Hello,

I have to tell you, we never got this program to work for us. I have notes that it could not find a program it needed to run (ete), and then both I am my student abandoned it once we got it working, because it would run for a few seconds, and then stop:

"That is exactly what I found with the GWideCodeML.   I tried several different ways to keep it running, including continuously hitting the return key in the terminal, but it would run a job only a few minutes and they never finished.  She might have used a version of ETE that was having that issue.  The author of ETE fixed that, but maybe she did not update the ete installed."

So sorry I can not help more!
Good luck to you!
Sher


Sher Hendrickson, PhD
***@***.***

Associate Professor of Biology, Shepherd University, Shepherdstown, WV
Research Associate, Smithsonian National Zoo and Conservation Biology Institute,  Center for Conservation Genomics,Washington, DC



________________________________

**Comment by lijunyuan** [comment]
Thanks for your promptly reply, Sher. Since GWideCodeML does not work by far, have you discovered other tools available online instead and do you mind recommending some user-friendly? 

With respects,
Junyuan 
Post doc, IOCAS, China

**Comment by Sher-Ojala** [comment]
Hello Junyuan!

I never did find a user-friendly method, but went back to using PAML following this paper:
Genome-wide signatures of complex introgression and adaptive evolution in the big cats

By Henrique V. Figueiró,et al. 2018

I used ETE3 directly on a set of genes we were interested in.

This fall, I am adapting it to use gene predictions,  but I have been distracted with aligning some new genomes.
Good luck!
Sher
________________________________
