### ISSUE TITLE
'Nodes are not connected'

### ISSUE THREAD

**Issue by jananiharan** [lauguma/GWideCodeML#7]
I'm using a species tree generated by OrthoFinder and the genome tags correspond to the names in my codon-aware alignment file. Here's the command and the output:

```
gwidecodeml -tree SpeciesTree_unrooted.txt -work_dir ~/HGT/flexible.dNdS/Orthogroup_Sequences/single.copy.fasta/codon.aware.alignments -cds .pal2nal -model BS -p 5 -branch branch_labels.csv -dnds

Traceback (most recent call last):
  File "/home/janani/anaconda3/envs/gwcodeml/bin/gwidecodeml", line 33, in <module>
    sys.exit(load_entry_point('gwidecodeml==1.1', 'console_scripts', 'gwidecodeml')())
  File "/home/janani/anaconda3/envs/gwcodeml/lib/python3.6/site-packages/gwidecodeml-1.1-py3.6.egg/gwidecodeml/__main__.py", line 134, in main
  File "/home/janani/anaconda3/envs/gwcodeml/lib/python3.6/site-packages/gwidecodeml-1.1-py3.6.egg/gwidecodeml/pkg_utils/utils.py", line 136, in prepare_codeml
  File "/home/janani/anaconda3/envs/gwcodeml/lib/python3.6/site-packages/gwidecodeml-1.1-py3.6.egg/gwidecodeml/pkg_utils/utils.py", line 527, in prune_tree
  File "/home/janani/anaconda3/envs/gwcodeml/lib/python3.6/site-packages/ete3/coretype/tree.py", line 532, in prune
    start, node2path = self.get_common_ancestor(to_keep, get_path=True)
  File "/home/janani/anaconda3/envs/gwcodeml/lib/python3.6/site-packages/ete3/coretype/tree.py", line 928, in get_common_ancestor
    raise TreeError("Nodes are not connected!")
ete3.coretype.tree.TreeError: 'Nodes are not connected!'
```

Happy to send any files that might be helpful in troubleshooting.

**Comment by jananiharan** [comment]
Issue fixed, it was a file formatting issue.

**Comment by HongboTang** [comment]
Hello, 
I didn't have a problem running the example_data, but I still had the same problem running my own data set. I wonder if there is a file problem?

**Comment by HongboTang** [comment]
gwidecodeml -tree review1_12pops.nwk -work_dir /home/0.project/1.duck/1.Comparative_genomics/review1/4.Codeml/ -cds .fna -model BS -branch Species.csv -p 20
    raise TreeError("Nodes are not connected!")
ete3.coretype.tree.TreeError: 'Nodes are not connected!'
